---
title: Abstract
---

# Abstract

Diel vertical migration (DVM) is a widespread phenomenon in aquatic environments. The primary hypothesis explaining DVM is the predation-avoidance hypothesis, which suggests that zooplankton migrate to deeper waters to avoid detection during daylight. Copepods are the predominant mesozooplankton undergoing these migrations, however they display massive morphological variation. Visual risk also depends on a copepod’s morphology. In this study, we investigate hypotheses related to morphology and DVM: (H1) as size increases visual risk, increases in body size will increase DVM magnitude and (H2) if copepod transparency can reduce visual risk, increases in transparency will reduce DVM magnitude. In-situ copepod images were collected across several cruises in the Sargasso Sea using an Underwater Vision Profiler 5. Copepod morphology was characterized from these images and a dimension reduction approach. While in-situ imaging offers challenges for quantifying mesozooplankton behavior, we introduce a robust method for quantifying DVM. The results show a clear relationship in which larger copepods have a larger DVM signal. Darker copepods also have a larger DVM signal, however only amongst the largest group of copepods and not smaller ones. These findings highlight the complexity of copepod morphology and DVM behavior.