---
bibliography: references.bib
---

# Introduction

Diel vertical migration (DVM) is a wide spread phenomena with large consequences in ocean ecosystems. DVM is the process of pelagic organisms vertically moving in the water column on a daily basis, often travelling dozens to hundreds of meters [@bianchi2016]. This large-scale event occurs across many taxa, from plankton to fish [@brierley2014]. However, DVM is particularly notable in zooplankton communities, whose migrations contribute substantially to biogeochemical cycles [@steinberg2017; @archibald2019; @siegel2023]. Mesozooplankton communities, largely dominated by copepods [@turner2004], will feed in surface layers of the ocean at night then migrate into deeper waters during daytime. Through this movement, copepods actively transport carbon to depth. Additionally, @kelly2019 described zooplankton DVM to be a major component of mesopelagic food webs. Thus to understand pelagic food webs and nutrient cycles, it is critically important to understand the drivers of DVM.

DVM has long been studied in marine systems [@bandara2021]. Predominantly, zooplankton DVM is the movement from deep waters at daytime to shallower waters at night [@hays2003; @bianchi2016]. However, reverse migration is also well documented [@ohman1990]. The adaptive benefits of DVM have been extensively reviewed [@lampert1989; @hays2003; @cohen2009; @ringelberg2009; @williamson2011; @bandara2021]. Some studies have hypothesized that DVM provides a physiological advantage. It has been suggested that moving to deeper waters may provide zooplankton a reduction in UV-damage [@ewald1912; @kessler2008], metabolic benefits [@mclaren1963; @enright1977], or demographic benefits [@mclaren1974]. However, the predator-avoidance hypothesis has received the most support to explain ultimate causes of DVM [see review of current evidence by @bandara2021]. First described by @Zaret1976, this hypothesis posits zooplankton evacuate the sunlit surface to evade visual predators then ascend at night to feed. However the massive migration undertaken by zooplankton is energetically expensive [@maas2018; @robison2020]. Therefore, the predator-avoidance hypothesis makes a clear prediction that the trade-off of expended energy is worth the predator avoidance benefit [@lampert1989]. This trade-off has been further described in observations of the relationship between zooplankton feeding and DVM patterns which led to the hunger-satiation hypothesis [@atkinson1992; @pearrejr.2003]. This hypothesis suggests that vertical migrators will ascend to feed when hungry then retreat once full. Once an individual has fully fed, remaining at the surface provides no benefit while their visual risk may increase due to their full guts which may increase visibility. Thus, the hunger-satiation hypothesis provides a detailed case of the predator-avoidance hypothesis and suggests cases where copepods may forego DVM. Regardless, both the hunger-satiation hypothesis and the predator-avoidance hypothesis suggest DVM is primarily a result of top-down control. In modelling studies with copepods, the predominant oceanic zooplankton, top-down control [@bandara2019] and trophic interactions [@pinti2019] have successfully been used to replicate DVM patterns.

Predator-driven migration suggests that DVM can be a function of an individual copepod's detection risk by a visual predator. However, this risk can depend on a copepod's morphological features [@aksnes1997]. Notably a copepod's size can increase visual detection. Several studies have documented that copepod size influences DVM magnitude [@hays1994; @ohman2016; @aarflot2019]. Presumably, a copepod's transparency will also influence DVM. @hays1994 reported that pigmentation explained variation in DVM frequency. However, few other studies have investigated this at length. One barrier to studying a relationship between copepod morphology and DVM is the difficulty of accurately recording traits. Several approaches have been utilized to study DVM. High spatiotemporal resolution of DVM can be achieved through acoustic [@liu2022], and even satellite-based measurements [@behrenfeld2019]. However these approaches do not yield information about individuals, much less traits. Net collected specimens can allow for trait-related investigations of copepod DVM patterns [@hays1994; @ohman2016]. However, it is much more challenging to measure traits related to copepod transparency from net-collected specimens. Copepods collected from deep net tows can be severely damaged and their gut contents may not reflect natural conditions due to cod-end feeding or regurgitation. Furthermore, typical preservation methods of net-specimens can result in the loss of pigmentation through bleaching in ethanol or formalin or increases in opacity as the copepod dies. Yet traits related to copepod's transparency are not well captured in net-collected specimens which may evacuate gut contents or lose pigmentation following preservation in formalin or ethanol. In @hays1994's investigation, the authors relied on previously published copepod carotenoid values in their analyses rather than attempt to measure pigment values from their preserved specimens.

However, these sampling challenges may be effectively circumvented with the emerging use of in-situ imaging tools. By directly observing copepods, new insights into their behavior and traits can be resolved [@ohman2019b]. For example, @whitmore2021 used an in-situ imaging device to describe a relationship between copepod abundance with a particulate field rather than chlorophyll-a. Such findings are facilitated by the fact imagery data records an individual's exact position. Additionally, a copepod's true appearance, including difficult to record metrics like transparency, can be measured. Thus, in-situ imaging offers a new perspective to investigate DVM hypotheses. Some studies observed a copepod DVM pattern with in-situ imagery data [@pan2018; @whitmore2021]. However, direct tests of DVM-related hypotheses with such data have not yet been conducted.

In this study, we utilized in-situ imaging to evaluate how copepod morphological traits influence DVM patterns. We specifically test the hypotheses that, (H1) as size increases visual risk, increases in body size will increase DVM magnitude and (H2) if copepod transparency can reduce visual risk, increases in transparency will reduce DVM magnitude. If these morphologically based hypotheses are true, then the larger and darker copepods will have the largest DVM magnitude.
