---
title: Scientific Significance Statement
bibliography: references.bib
---

## *Scientific Significance Statement*

### Study Novelty

Diel Vertical Migration is a widespread phenomenon across marine and freshwater systems. The predator evasion hypothesis suggests that DVM occurs as zooplankton attempt to escape visual predators. Yet, DVM itself is a costly and risky behavior. Thus, DVM should only occur when visual risk is high. Several studies have shown that copepod size influences the magnitude of DVM. However, an individual’s visual risk may include traits beyond simply size. In this study, we utilize an in-situ imaging tool to reveal how copepod morphological traits influence DVM. Our findings show that both size and transparency influence DVM. We support this finding through rigorous statistical analyses and state-of-the-art technology. This finding provides support for leading DVM hypotheses and highlights that DVM is a complex behavior driven by multiple copepod traits. Furthermore, this study represents a novel application of in-situ imaging technology to address major hypotheses in biological oceanography.

### Applicability to L&O

This study addresses diel vertical migration, an active, major research topic in biological oceanography. Many studies published in L&O contribute to advancing knowledge on DVM. In this paper, we provide strong evidence for both size and transparency influencing DVM behavior. Additionally, we accomplished this study using emerging technology and statistical analyses. This work builds on research published in L&O and will be broadly applicable to plankton ecologists, biological oceanographers.