---
title: Methods
bibliography: references.bib
---

# Methods

## CTD profiles and UVP imaging of copepods

Data were collected aboard the R/V Atlantic Explorer in collaboration with the Bermuda Atlantic Time-series Study (BATS) [@steinberg2001]. In-situ images of plankton were acquired using an Underwater Vision Profiler (UVP5) [@picheral2010]. The original sampling methodology and instrument specification followed details described in @barth2022. The UVP was attached to the CTD rosette and deployed regularly on cruises to the Sargasso Sea from June 2019 - December 2021. Typical monthly cruises included \~13 profiles with average descents to 1200m (Supplemental Figure 1). In this study, we investigated general trends in DVM by pooling together casts across multiple cruises. This approach is necessitated by the small sampling volume of the UVP (1.1L/image) and low abundance of plankton which requires aggregation of data to resolve trends [see details in @barth2022]. While there was minor variation between cruises (Supplemental Figure 2), this oligotrophic system is relatively consistent across seasons [@steinberg2001]. Additionally, every cruise had an approximately equal number of day and night casts. Profiles were assigned to be day or night based on locally calculated nautical dawn and nautical dusk times using the R package `suncalc 0.5.1`.

The UVP records images of large particles (\>600$\mu$m equivalent spherical diameter, ESD). However, living particles are not reliably identifiable below 900$\mu$m [@barth2022]. All recorded images were processed using Zooprocess [@gorsky2010], which provides several metrics related to size, grey value, and shape complexity. These features were then used to automatically sort images using Ecotaxa [@picheral]. All images were manually verified by the same trained taxonomist. In total, 294,913 images were recorded. Of these, 85.2% were images of debris or artefacts. The smallest identified copepod was 0.940mm ESD and the largest was 5.904mm ESD. Across all casts, copepods were the most common organism, composing 58.7% of all identified, living particles. In total, there were 4151 individual copepods images.

## Morphological Grouping

Zooprocess measures and collects several morphologically relevant parameters. To create relevant groups of copepods, a dimension reduction approach was used. Similar methods have been successfully utilized to provide novel insights to marine snow [@trudnowska2021], copepod dynamics in the Arctic [@vilgrain2021], and temporal trends in phytoplankton communities [@sonnet2022]. First, 18 morphologically relevant parameters were selected to be included in a Principal Components Analysis (PCA), following [@vilgrain2021]. Parameters can be described as relating to size (e.g. major axis, equivalent spherical diameter \[ESD\]), grey intensity (e.g. mean grey value at 625nm wavelength light), shape (e.g. elongation, symmetry), and shape complexity (e.g. fractal dimension). This morphospace approach has several advantages.

First,

Furthermore, in the context of this study, there are several factors which influence copepod transparency which are not easily distinguishable in most UVP images. If only one metric was selected it may only capture one aspect of transparency, thus by including all factors, we can distinguish the major sources of variability across all observed copepods.

The PCA was weighted by the volume sampled in a 1-m depth bin for each observation. This approach provides a correction for the UVP's variable descent speed which can cause duplicate imaging of individuals. While this phenomena has a minor impact on overall results [@barth2022], we used the weighted approach to assure that no individual features were overrepresented. All morphological descriptors were scaled and centered prior to inclusion in the analysis. The model was constructed using the R package `FactoMineR 2.7`. Principal Components (PCs) were deemed to be significant if their eigenvalues were greater than 1. This approach yielded 4 PCs which described 87.3% of the total variation in morphological parameters, with 34.5% and 26.5% in the first two components respectively. The third and fourth PCs were related to the orientation of the copepod and appendage visibility respectively. Presumably, this is an artifact of how the copepod was imaged. Because all axes in a PCA are orthogonal to one another, the variation described in PC1 and PC2 can then be assumed to be independent.

To address our morphology-DVM hypotheses, we constructed discrete morphological groups based on the first two principal components. Groups along each of the principal components were defined as low (below 25th percentile), mid (25th-75th percentile) and high (greater than 75th percentile). To address the size-dependent hypothesis (H1), groups were assigned as low, mid, or high along PC1. Then to assess if color/transparency was a secondary factor (H2), within each PC1 group, PC2 groups were constructed as low, mid, or high. In total, this created 9 groups (e.g. Low PC1-Low PC2, Low P1-mid PC2, etc).

## Copepod vertical structure & DVM

### Vertical distribution of copepods

Copepods in this system are well documented to undergo DVM [@steinberg2000; @schnetzer2002; @maas2018]. However, there have not been direct measurements of DVM with in-situ imaging data. First, to assess which portion of the water column copepods were utilizing for DVM, we visualized the average vertical structure. The concentrations of each morphological group (based on PC1 and PC2) were calculated in 20m depth bins for each UVP profile. Profiles were designated as either day or night. Then across all day/night profiles, the mean concentration was calculated for each 20m depth bin.

### Weighted mean depth variability

Weighted mean depth (WMD) is a common metric to describe vertical structure and DVM in zooplankton [@ohman2002; @ohman2016; @aarflot2019]. However, with in-situ imagery, this approach presents a few challenges. WMD cannot be calculated individually for each profile then averaged because each profile had a different descent depth. Additionally, the small and uneven sampling volume of the UVP can make single casts too variable to reliably resolve abundance. Yet, understanding variation around the WMD is necessary to compare DVM strength across groups. Here, we introduce a depth-bin constrained bootstrap approach to define WMD with a 95% confidence interval. To do this, the concentration of each group, was calculated in 20m depth bins for each profile. Then all profiles were 'pooled', separately for day/night. This provides a distribution of concentrations in each depth-bin. However, due to the different descent speeds and depth of profiles, there are more observations of surface depth bins. Thus, traditional bootstrapping would bias estimate toward the surface as resampling would be more likely to draw a more-frequently observed surface bin. To avoid this, bootstrap samples were "bin-constrained" such that for each iteration, a random observation was drawn within each depth bin, then replaced for the next iteration. A maximum depth was set to 600m based on qualitative observations of vertical profiles. This approach effectively created a random profile by resampling a concentration, $conc^*$, from each depth bin, $d$. For each iteration, the random constructed profile then was used to calculate a bootstrapped weighted mean depth, $WMD^*$. This was done for each morphological group, $g$, at each time of day, $t$ (day/night).

$$WMD^*_{g,t} = \sum_{i}^{N = 30}{\frac{d_i(conc^*_{i,g,t})}{\sum_i^{N = 30}{conc^*_{i,g,t}}}}$$

The distribution of $WMD^*_{g,t}$ then was used to calculate a bootstrapped mean and 95% confidence interval. The width of the confidence interval then is influenced both by the spread of copepods through the water column and the amount of data available to confidently support their estimates. Thus, this resampling approach is conservative in identifying a significant trend. The conservative approach is desirable given both its robustness to UVP sampling variability and the need to pool casts as described above.

To assess a signficant DVM pattern, he 95% CIs could be compared between times of day and morphological groups. While the DVM magnitude can be measured by comparing the mean $WMD^*$s, we identify a "clear DMV signal" as when there is no overlap between the 95% WMD CIs between nighttime and daytime groups. Using PC1 to assess size, the WMD was compared between the three PC1-groups by percentile level. Then to assess the effect of transparency the WMD was compared between PC2-groups within each PC1-grouping. A larger signal of DVM would be evident by a clearly deeper (non-overlapping 95% CI) daytime WMD.
