---
title: Discussion
bibliography: references.bib
---

# Discussion

## Copepod morphospace & quantifying DVM

In this study, we built on methods for describing morphospaces from similar in-situ imaging studies [@trudnowska2021; @vilgrain2021; @sonnet2022]. The PCA-defined morphospace with the present data aligns well with the prior applications. Interestingly, the proportion of morphological variation explained by each axis in the morphospace defined on Arctic copepods by @vilgrain2021 is extremely similar to the morphospace axes in this study. This similarity is striking considering the vastly different copepod community compositions between the Arctic ocean and subtropical gyres [@soviadan2022]. The similarity of morphospaces could also be an artifact of the similarity of input data. Given the UVP has a limited range of observable size classes [@picheral2010], only copepods above a certain size were fed into both PCAs. Alternatively, the similarity of studies suggest that copepod morphological variation might be well described by these two primary axes. [@sonnet2022] used phytoplankton images to investigate how a morphospace could be used to evaluate community composition changes over time. Comparisons of copepod morphospaces across temporal and spatial scales may offer a useful metric for answering biogeographic and ecological questions.

While the UVP provides some methodological challenges to quantifying DVM, the pattern of DVM described in this study is consistent with the commonly observed nocturnal DVM pattern [@bianchi2016; @bandara2021]. The average vertical profiles display a clear day/night difference (Figure 3). However, in each 20m depth bin there was large variation, often exceeding the average concentration. This large variation was expected. There can be considerable variation between UVP estimates of zooplankton abundance [@barth2022]. Additionally, in this study we pooled casts across multiple seasons. Variability in copepod DVM has been described across seasons [@whitmore2021]. However, in the Sargasso Sea, while there is seasonal variation in DVM biomass [@behrenfeld2014], there is no record of variation in DVM magnitude. Other studies describing DVM in the region have also pooled across seasons using net data [@ivory2019]. Thus, while pooling across seasons may have introduced some variability in our WMD estimates, the DVM signal was still well described by the UVP. Previous studies using in-situ imaging have also noted a signal of DVM with copepods [@pan2018; @whitmore2021]. Yet due to small and uneven sampling, it can be a challenge to quantify DVM using in-situ imaging. As presented in this paper, bin-constrained bootstrapping offers a robust method to quantify WMD and investigate DVM hypotheses.

## Morphological variation in DVM

The results presented in this study provide new perspective on how traits influence DVM patterns. Consistent with the size-based hypothesis (H1), we documented a clear effect in which larger copepods migrated further. This finding is consistent with several studies which have documented a size-dependent relationship for copepod DVM [@ohman2016; @aarflot2019; @pinti2019]. @ohman2016 noted that moderate-size copepods had the largest migrations. While this may seem contradictory to the present study, the difference between study systems needs be taken into account. The copepods described in the large (high PC1) group had a mean feret diameter of nearly 5mm. Conversely, in @ohman2016's study the "moderate" copepods ranged from 4mm-6mm.

The transparency-based hypothesis (H2) was only supported by patterns within the large copepod group. The large but more transparent copepods (low PC2, high PC1) did not have a detectable DVM signal. Yet the darker copepods (mid and high PC2) had a large DVM signal. It should be noted that the grey-value recorded by the UVP may be indicative of many features which influence copepod pigmentation, including pigmentation, egg-sacs and gut contents [@vilgrain2021]. Thus, while our observation is consistent with both the predator-avoidance and the hunger-satiation hypotheses, we cannot distinguish exactly why the large, more transparent copepods do not migrate. One possibility is that these copepods have empty gut contents, and thus are less transparent and motivated to feed near the surface. However it is aslo plausible that the difference in transparency is driven by taxonomic differences in pigmentation. UVP images of copepods are generally unidentifiable to higher taxonomic resolution. However, it is likely that the majority of copepod images were Calanoida, which are consistently reported as the dominant copepod group in the Sargasso Sea [@deevey1977; @ivory2019; @blanco-bercial2020]. Additionally, a long-term analysis of net-collected data reported only Calanoida to show a significant DVM signal [@ivory2019]. However, within this group, there is extreme diversity [@deevey1977; @blanco-bercial2020]. In a metabarcoding study of the epipelagic mesozooplankton community, @blanco-bercial2020 reported *Pleuromamma spp.,* Euchaetidae, and Eucalanoidea to show higher nighttime relative abundance. Alternatively, Calanidae were described to occupy the surface waters at daytime. Thus, while the present study cannot make direct conclusions as to taxonomic variation, it is likely a driving factor in DVM variability across the observed morphological groups.

@hays2003 described that copepod pigmentation could explain increased DVM with small (\<1mm) copepods. Thus it was surprising that there was no effect of transparency on DVM magnitude in the smaller morphology group. One possibility is that the small, transparent copepods were not well sampled by the UVP (Figure 2). Due to the conservative nature of the bootstrapping WMD approach utilized in this study, sampling deficits would broaden the 95% WMD CI's, reducing the ability to resolve trends. However, there is no observable trend to suggest the lack of DVM signal is simply a methodological artifact. Alternatively, there are several possible explanations for why there is no effect of transparency for the smaller copepod morphological groups. First, it should be noted that while both the small-sized (low PC1) and mid-sized (mid-PC1) group showed no variation in DVM patterns across PC2, the mid-sized group consistently showed a strong DVM signal while the small-sized group did not. Amongst the small-sized group, there was little observable DVM across all transparency groupings. It may be that these copepods have a low visual-predator risk regardless of their transparency level. @ohman2016's study in the California Current observed that the smallest copepods (\<1.5mm) displayed no DVM signal. While these copepods may have reduced predator risk, it may also be that they simply are weaker swimmers and cannot reasonably migrate as large of distances as bigger copepods can.

The mid-sized copepods display a clear DVM signal across all transparency groupings. This suggests that mid-sized copepods do not relieve their predation risk through increased transparency. This is counterintuitive to the observation that the large, transparent copepods have a reduced DVM signal. Additionally the transparent, mid-sized copepods migrating while the transparent, large ones do not, directly contradicts the predator-avoidance hypothesis. It is worth noting that DVM behavior can also vary greatly across species. Within migrating nekton, there has been mixed support described for the hunger-satiation hypothesis, depending on taxa [@bos2021]. Thus again it may be taxonomic variation which can explain deviations in expected DVM patterns. Additionally, other mechanisms influencing DVM, asides from top-down factors may be at play. @williamson2011 provides support for the transparency-regulator hypothesis of DVM, which suggests both top-down factors and environmental factors such as UV-radiation influence DVM behavior. In the Sargasso Sea, there is extreme water clarity which would suggest UV-radiation may play a role in DVM behavior. However, none of our findings suggest that more pigmented copepods migrate less than transparent ones, regardless of size. Yet, across all copepod morphological groups, abundances were highest in the mid-to-lower mesopelagic and low in the surface layers (Figure 2). Thus the copepods imaged in this study are likely already at layers below where UV damage is a major factor. Furthermore, the deep chlorophyll-a maximum regularly extended into low epipelagic (Supplemental Figure S2), providing sufficient food where UV irradiance is low. Nonetheless, while UV may not be a primary factor, the notion that there are multiple factors influencing DVM should be considered.

## Conclusion

Overall, our results reveal a complex dynamic between copepod traits and DVM behavior. This study provided new insight into the DVM dynamics in oligotrophic gyres. While many studies have established size as a major trait influencing DVM, investigations into other traits are more limited. Here, we support the prevailing notion that size has large consequences for DVM behavior. We also show that transparency has an effect on DVM for some size groups. However, determining exactly which drivers determine why copepods with different traits undergo diel vertical migration remains elusive. While these findings are largely consistent with the predator-avoidance hypothesis and prevailing DVM theory, they highlight the need for more detailed analyses. As plankton in-situ imaging tools are used more commonly by oceanographers, larger datasets will facilitate new investigations. Additionally, improved resolution of sampling tools may better determine taxonomic variation. Collaborations between oceanographers, plankton ecologists, and visual ecologists may better resolve how traits influence trade-offs in DVM behavior. Understanding these dynamics will be critical to predicting changes with a changing ocean.
