---
title: Size and transparency influence diel vertical migration patterns in copepods.
bibliography: references.bib
csl: './limnology-and-oceanography.csl'
execute:
  echo: false
  warning: false
  message: false
author:
  - name: Alex Barth*
    affiliations:
    - name: University of South Carolina
      department: Biological Sciences
      address: 700 Sumter St 401, Columbia, SC 29208
  - name: Rod Johnson
    affiliations: 
    - name: Bermuda Institute of Ocean Sciences
      address: Bermuda GE 01, UK
  - name: Joshua Stone
    affiliations:
    - name: University of South Carolina
      department: Biological Sciences
      address: 700 Sumter St 401, Columbia, SC 29208
format:
  pdf:
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex"
    include-in-header:
      - "in-header.tex"
    number-sections: true
    linestretch: 2
    tbl-cap-location: top
    filters: [wordcount.lua]
---


```{r}
#| child: ./00_science-sig-statement.qmd
```


```{r}
#| child: ./00_author_contributions.qmd
```


```{r}
#| child: ./00_abstract.qmd
```


```{r}
#| child: ./01_intro.qmd
```

```{r}
#| child: ./02_methods.qmd
```

```{r}
#| child: ./03_results.qmd
```

```{r}
#| child: ./04_discussion.qmd
```

```{r}
#| child: ./05_acknowledgements.qmd
```

## References
::: {#refs}
:::


```{r}
#| child: ./06_data_availability.qmd
```


```{r}
#| child: ./Supplemental Information.qmd
```

