---
title: Methods
bibliography: references.bib
---

# Methods

## CTD profiles and UVP imaging of copepods

Data were collected aboard the R/V Atlantic Explorer in collaboration with the Bermuda Atlantic Time-series Study (BATS) [@steinberg2001]. In situ images of plankton were acquired using an Underwater Vision Profiler (UVP5-DEEP, sn: 209, Hydroptic, [@picheral2010]). The original sampling methodology and instrument specification followed details described in [@barth2022]. A brief summary of new and relevant sampling methodology are described below. The UVP was attached to the CTD rosette aboard the R/V Atlantic Explorer. The UVP was equipped for monthly cruises into the Sargasso Sea from June 2019 - Aug 2019 and October 2020 - December 2021. A typical monthly cruise included 13 profiles with descents typically to 1200m. Full cast details are available in Supporting Information. Only profiles within the BATS region were included (Figure 1). Generally, as described in analyses below, it was assumed that profiles within the BATS region during a cruise sampled a similar water mass. While mesoscale features are known to drive variability in this region, there were no major variations within a cruise (Supplemental Figure 1). The CTD collected continuous environmental parameters on down-casts, including temperature (Dual SBE-03f, Sea Bird Scientific), conductivity (Dual SBE04, Sea Bird Scientific), dissolved oxygen (SBE43, Sea Bird Scientific) and fluorescence (Chelsea Instruments). Because the purpose of this study was to investigate day/night differences in copepod vertical distributions, it was important that there were day and night casts during each cruise. It would be ideal to investigate each profile, without pooling the entire region by cruise, however, the small sampling volume of the UVP and low abundance of plankton in this region create the need to pool or average profiles [@barth2022]. Profiles were assigned to be day or night based on locally calculated nautical dawn and nautical dusk times using the R package `suncalc 0.5.1`.

```{r, fig.height=3.5, fig.width=3.5, fig.align='center', fig.cap='Figure 1. Map of CTD and UVP profiles used in the study. Day and night points from all cruises are shown. Bermuda is shown in green.'}
library('ggplot2')
library('rnaturalearth')
library('rnaturalearthdata')

# |- get spatial data ----------
world <- ne_countries(scale = 'medium', returnclass = 'sf')

# |- read in data -----------------
cast_loc <- readRDS('../data/01_ctd-locations.rds')

all_cast_map <- ggplot()+
  geom_sf(data = world, fill = 'green')+
  geom_point(aes(x = -cast_loc$lon, y = cast_loc$lat,
                 shape = cast_loc$tod, col = cast_loc$tod),
             position = position_jitter(width = .05, height = 0.05))+
  coord_sf(xlim = c(-65,-62), ylim = c(30,33))+
  theme_bw()+
  labs(x = "",y = "", shape = "", color = "")+
  scale_color_manual(values = c('beige','black'))+
  theme(panel.background = element_rect(fill = 'cornflowerblue'),
        panel.grid = element_line(color = 'lightgrey', linetype = 'dotted'),
        axis.text.x = element_text(angle = 45, hjust = c(1,1)),
        legend.position = c(0.9,.2),
        legend.background = element_blank(),
        legend.box.background = element_rect(fill = 'lightgrey'),
        legend.key = element_rect(fill = 'lightgrey'),
        plot.background = element_blank())

print(all_cast_map)

```

The UVP sampled during down-casts of all profiles at a rate of \~15Hz. The UVP records counts of small particles (\>184$\mu$m Equivalent Spherical Diameter, ESD) and images of large particles (\>600$\mu$m ESD). However, living particles are not reliably identifiable below 0.9 mm [@barth2022]. All recorded images were processed using Zooprocess [@gorsky2010], which provides several metrics related to size, grey value, and shape complexity. These features were then used to automatically sort images using the Ecotaxa application [@picheral]. While automatic classification increases the overall speed of identification [@irisson2022], all images were manually verified by the same trained taxonomist. In total, 294913 images were recorded. Of these, 85.2% were images of debris, marine-snow, or artefacts, while 14.8% were identified as living. In the present study, only copepods were investigated. The smallest observed and identified copepod was 0.940 mm ESD and the largest was 5.904 mm ESD. Across all casts, copepods were the most common observed organism at 58.7% of all identified, living particles. In total, there were 4151 individual copepods investigated in this study.

## Identification of morphogroups classification

To test the hypothesis of morphological influences on DVM magnitude, copepod images were classified into distinct morphological-groups (referred to as morphogroups). The UVP automatically measures and collects several morphologically relevant parameters. To create relevant groups of copepods, a dimension reduction and clustering approach was used. Similar methods have been successfully utilized to provide novel insights to marine snow [@trudnowska2021], copepod dynamics in the Arctic [@vilgrain2021], and temporal trends in phytoplankton communities [@sonnet2022]. First, 18 parameters were selected to be included in a Principle Components Analysis (PCA) which represent major copepod morphological features following [@vilgrain2021]. Parameters can be described as relating to size (e.g. major axis, feret diameter, ESD), grey intensity (e.g. mean grey value), shape (e.g. elongation, symmetry), and shape complexity (e.g. fractal dimension, perimeter/feret). All parameters and model structure are available in Supporting Information. The PCA was weighted by the volume sampled in a 1-m depth bin for each observation included in the model. This approach provides a correction for the UVP's variable descent speed which can cause duplicate imaging of individuals. While this phenomena has a minor impact on overall results[@barth2022], we used the weighted approach to assure that no individual features were over represented. An unweighted PCA did not produce substantially different results, which supports the notion that duplicate images are a minor phenomena. All morphological descriptors were scaled and centered prior to inclusion in the analysis. The model was constructed using the R package `FactoMineR 2.7`. Principle components were deemed to be significant if their eigenvalues were greater than 1. This approach yielded 4 PCs which describe 87.3% of the total variation in morphological parameters, with 34.5% and 26.5% in the first two components respectively. This four principle component space provides a "morphospace" to characterize copepods.

Then to classify distinct morphogroups, a k-means clustering algorithm was used on the principle components [@trudnowska2021]. While, there were 4 significant PCs, only the first two were used in the k-means clustering. Similar to @vilgrain2021, the third axis could be described by the orientation of the copepod to the camera and the fourth axis could be used to describe appendage visibility. Presumably, the both these factors would be random with respect to the depth at which a copepod was found. Possibly, appendage visibility could have a relationship with feeding activity, yet when included in the cluster analysis, no group clearly separated along this axis. Thus for simplicity, only the first two axes were included in the k-means clustering algorithm. To select the optimal number of clusters, clusters were added until the addition of a new cluster would not produce an increase the overall explanatory power ($\frac{WithinSS}{TotalSS}$) by more than 10%. This process identified four distinct morphogroups. The k-means clustering algorithm was ran with 1000 random starts. All code for the PCA and k-means models can be found in the supporting information. Additional model diagnostics are available in Supporting Information 2.

## Investigating copepod vertical structure

Copepods in this system are well documented to undergo DVM [@steinberg2000; @schnetzer2002; @maas2018] However, direct measurements of DVM using in situ imaging are not common. Thus, there are not established methods to describe DVM differences between groups or relation to environmental parameters. Here, we use and evaluate several approaches to specifically test DVM variation between morphogroup and in response to environmental factors. These include both classic and novel methods.

### Vertical distribution of copepods

To visualize copepod vertical structure across morphogroups, the concentration of each morphogroup was calculated in 20m depth-bins for each UVP profile.

These binned-profiles were then averaged together based on time of day. This average-cast approach is useful as it provides a general pattern with information as to the variability between casts. Then to better estimate the day-night differences within each morphogroup, a proportional difference was calculated in each depth bin. A morphogroup's proportional difference was defined for each $i$ depth bin as $Prop\ Diff_i = \frac{Night_i - Day_i}{\sum^N_i Night_i + Day_i}$, where $Night_i$ and $Day_i$ are the average concentrations in that bin. By scaling each bin's diel difference by the total morphogroup concentration, it is possible to compare the profiles of proportional difference without the influence of difference in total concentration between morphogroups or depth bins. The proportional difference profile then was used to select a maximum depth (600m) to include for the weighted mean depth calculations.

### Weighted mean depth variability

Weighted mean depth (WMD) is a common metric to describe vertical structure and DVM in zooplankton ***CITE***. However, with in-situ imagery, this approach presents a few challenges. WMD cannot be calculated individually for each profile then averaged because each profile had a different descent depth. Similarly, profiles had different sampling efforts throughout the water column. So to calculate the WMD for each morphogroup and each time of day, all 20-m binned concentrations from (0,20\] and (580, 600\], were pooled together. Then a bootstrap method was used to describe the variability in profiles and vertical structure. A traditional bootstrap approach would not work however, because there were more instances of shallow depth bins (as not all casts went as deep) so it would bias estimates. To correct for this, we define a bin-constrained approach to estimate a bootstrapped $WMD^*$.

$$
WMD^*_{mg, tod} = \sum_{i}^{N = 60}{\frac{d_i(conc^*_{i,mg,tod})}{\sum_i^{N = 60}{conc^*_{i,mg,tod}}}}
$$

For each morphogroup ($mg$) and each time of day ($tod$), the $WMD^*$ was calculated by randomly sampling a concentration from the pooled distribution of concentrations for each depth bin \$i\$. This was done for all 60 depth bins above 600m. The concentration was then multiplied by the midpoint of the depth bin and divided by the sum of all randomly sampled concentrations. This process was iterated 999 times to create a distribution of $WMD^*$ for each morphogroup and time of day. For each iteration, the concentrations for a depth bin were randomly drawn with replacement for the next iteration. This approach effectively simulates multiple even profiles over the entire study region using the data from existing profiles. Then a bootstrapped mean and 95% confidence interval were calculated from that distribution of $WMD^*$. The the bootstrapped confidence interval can then be interpreted as wider for both variability between UVP profiles and the overall spread of the zooplankton in the water column. Consequentially, it can be said a morphogroup exhibits a clear/significant signal of DVM if the confidence intervals are non-overlapping between day and night.

### Occupancy modelling of vertical structure

While the bootstrapped WMD depth is useful for investigating broad-scale DVM patterns across the whole data set, it is a less effective when separating the data set into specific months and seasons. Again issues arise with the compounding effect of the UVP's low sampling volume and the rarity of organisms in this oligotrophic system. As described in detail by @bisson, when sampling volumes are low estimating the theoretical probability of correctly estimating particle concentration greatly decreases. In the present system, when specific morphogroups are quite rare for a given season or month, the estimate of concentration greatly depends on the presence/absence of that taxa in a depth bin and is not reliable as a result. To investigate the environmental impact on DVM, the vertical structure needs to be compared across cruises, or at least seasons. Therefore, using the WMD approach is not applicable because the split data sets would be too small.

Here, we investigate the novel application of site-occupancy models to this data set. Site-occupancy models are a hierarchical-model popularized in biogeography and conservation biology [@kéry2010, @kéry2008; @mackenzie2017]. Often used with presence/absence data, the fundamental concept behind site-occupancy models is that the process of observing an organism at a given location is a function of the probability the organisms is there (occupancy/occurrence probability, $\psi$) and the probability of detecting the organism given the sampling methodology (detection probability, $p$). These are an attractive class of models to apply to zooplankton in-situ imaging data because the detection probability is likely influenced by the sampling volume of the instrument while the occupancy is likely influenced by environmental/biological factors. To construct a site-occupancy model which estimates detection probability, replicate "surveys" must be done to each "site". For our data set, we define a "site" as a depth-bin on a particular cruise and a "survey" as a single UVP profile on that cruise. Conceptually this assumption is similar to pooling-casts together over a study area. To first validate the application of this model, we constructed a simple model using the presence/absence of all copepods (regardless of morphogroup).

$$
Y_{ij,db,tod} \sim Bernoilli(p_{ij,tod}*z_{i,db,tod})
$$$$
z_{i,db,tod} \sim Bernoulli(\psi_{db,tod})
$$$$
logit(p_{ij,tod}) \sim a_0 + a_{vs,tod} * vs_{ij}
$$

In this model, the event of observing a copepod at site $i$ during survey $j$ , for each depth bin $db$ and time of day \$tod\$, is a function of the observation process which is modeled by a Bernoulli process. The observation process occurs with the probability of the product of the detection probability, $p\_{ij,tod}$, and the occupancy, $z_{i,db,tod}$. This model was ran for each depth-bin (20m intervals from 0-1200m) and each time of day (day or night). The occupancy ($\psi$) , was assumed to be a unique, independent probability for each depth bin while the detection probability was modelling using a logistic regression to include the effect of volume sampled ($\alpha_{vs,tod}$). If the site occupancy model is effective in this system, it would be expected that there would be a positive effect of volume sampled on the detection probability. The models were ran three separate times, to estimate detection probability differences between the epipelagic (0-200m), upper mesopelagic (200-600m), and lower mesopelagic (600-1200m). Detection probability was likely to differ between these regions due to differences in UVP descent speed and thus sampling volume through the water column as described in [@barth2022].

Following the general all copepod model, we repeated the model yet separating out the different morphogroups. This allowed the test of the method to describe DVM. If effective, it would be expected there to be a difference in occupancy between daytime and nighttime in regions where migration is occurring (near-surface to upper mesopelagic). This additionally provides another method to test the hypothesis (H1) that morphology will increase DVM behavior, as it would predict the difference in day/night occupancy would be larger for more visually conspicuous morphogroups.

Finally, to evaluate the hypothesis that environmental conditions would influence DVM behavior, a site-occupancy model was constructed with included environmental parameters into the biological process for occupancy. Several metrics were selected to be included in the model. Two metrics corresponding to light availability were included, photosynthetically active radiation (PAR) and the diffuse attenuation coefficient ($\frac{1}{k_{490}}$). @ohman2016 described a clear relationship between increasing $\frac{1}{k_{490}}$, or deeper light penetration into the water column, and increased DVM amplitude. As such, in the present system, it was predicted that increases in PAR and $\frac{1}{k_{490}}$ would have a negative effect on daytime occupancy in depth bins near the surface. PAR and $\frac{1}{k_{490}}$ were both obtained from the Aqua MODIS sensor [@nasa2014] in 4km resolution in a grid encompassing the entire study area (Figure 1). Satellite data were collected with daily resolution yet averaged together over a cruise period because they were being modeled as "site" covariates. Metrics related to food availability were included as well. The depth of the deep chlorophyll-a maximum (\$DCM_d\$) was included with the prediction that a deeper $DCM_d$ would have a positive effect on deeper depth bin occupancy and a negative effect on shallower depth bin occupancy. This logic suggests that copepods are not likely to travel to the surface if there is not food available there. The $DCM_d$ was calculated from CTD profiles concurrent with the UVP then averaged together over the course of a cruise as a site covariate. CTD data were accessed from (http://batsftp.bios.edu/BATS/ctd/) using the R package `batsFtpReadR 0.1.0` (https://github.com/TheAlexBarth/batsFtpReadr). Finally the particle concentration \<450$\mu$m was included as it can be a useful representative of the zooplankton prey field [@whitmore2021; @gastauer2022]. Here, we use the integrated epipelagic (\<250m) prey field with the prediction that a decrease in epipelagic food would have a negative impact on occupancy in that region of the water column. All particle data were recorded with the UVP and the integrated epipelagic prey field was averaged across all casts on a cruise as a site covariate.

The full environmental model can largely follows the general site-occupancy model described above. However, in this model, the biological process that a site $i$ would follow the occupancy, or occurrence probability as modeled by a logistic regression. This was conducted with distinct intercepts (separate models) for each time of day, depth bin, and morphogroup.

$$
z_{i,db,tod,mg} \sim Binomial(\psi_{i,db,tod,mg})
$$$$
\begin{aligned}
logit(\psi_{i,db,tod,mg}) \sim \beta_{0_{db,tod,mg}} + \beta_{dcm\_d_{db,tod,mg}} * dcm\_d_i + \beta_{prey_{db,tod,mg}} * prey_i \\ + \beta_{par_{db,tod,mg}} * par_i +  \beta_{\frac{1}{k_{490}}_{db,tod,mg}} * \frac{1}{k_{490}}_{db,tod,mg}
\end{aligned}
$$

Thus there was a separate effect for each parameter $\beta$ on a depth bin ($db$), time of day ($tod$), and morphogroup ($mg$) . This allows for the investigation of how the posterior credible interval for the slope of each effect changes with depth.

All site-occupancy models follow a Bayesian hierarchical structure. These models were simulated using JAGS ver 4.3.1 using the R package `jagsUI 1.5.2`. All parameters were given vague priors. For fixed probabilities ($\alpha_0$, $\psi$ in the general model, \$\\beta_0\$), a Beta(1,1) prior was used. For all slope parameters ($\alpha_{vs}$, all $\beta$'s), a weak normal ($\mu$ =0, $\sigma$ = 1/10) was used. The MCMC algorithm was ran with three chains for 10,000 iterations. Chains were thinned at a rate of 2. All data used to inform slope parameters were standardized prior to inclusion to reduce autocorrelation.

## Data availability

All data and code are made available via (https://github.com/TheAlexBarth/DVM_Migration-Morphology). All supplemental figures, tables, and analyses are hosted on a public static site (https://thealexbarth.github.io/DVM_Migration_Morphology). This content is also available in the Supporting Information.
