project:
  type: website

website:
  title: "Migrator Morphology"
  navbar:
    background: dark
    search: false
    right:
      - href: index.qmd
        text: Home
      - text: Main Analyses
        menu:
        - href: main_01_morphospace.qmd
          text: PCA-Morphospace & Groups
        - href: main_03_Vert-Distrib.qmd
          text: Vertical Profiles
        - href: main_04_WMD-by-morphogroup.qmd
          text: Weighted Mean Depth Analysis
        
      - text: Supplemental
        menu:
        - href: supp_01_uvp-cast-info.qmd
          text: UVP Cast Info
        - href: supp_02_ctd-interp.qmd
          text: Physical Parameters
        - href: supp_03_pc-extended-info.qmd
          text: Extended PCA Info
        

    tools:
      - icon: github
        href: https://github.com/TheAlexBarth/DMV_BATS
      - icon: house-fill
        href: https://thealexbarth.github.io/#about

format:
  html:
    theme: journal
    css: styles.css
    code-fold: true
    code-tools: true
    
execute: 
  warning: false

editor: visual
