project:
  type: website

website:
  title: "Migrator Morphology"
  navbar:
    background: dark
    search: false
    right:
      - href: index.qmd
        text: Home
      - text: Main Analyses
        menu:
        - href: main_00_CTD-UVP-map.qmd
          text: Sampling Region
        - href: main_01_ctd_interp.qmd
          text: Physical Backdrop
        - href: main_02_PC-Clusters.qmd
          text: PCA-Morphogroup clustering
        - href: main_03_Vert-Distrib.qmd
          text: Vertical Profiles of MGs
        - href: main_04_WMD-by-morphogroup.qmd
          text: Weight Mean Depth of Morphogroups
        - href: main_05_all-copepod-occupancy.qmd
          text: All Copepod Occupancy Model
        - href: main_06_cluster-occurence.qmd
          text: Occupancy by Morphogroup
        - href: main_07_environmental-effect-model.qmd
          text: Environmental Effects on Occupancy
        
      - text: Supplemental
        menu:
        - href: supp_01_ctd-by-cruise.qmd
          text: CTD by Cruise
        - href: supp_02_pc-extended-info.qmd
          text: Extended PCA/Clustering Plots
        - href: supp_03_cluster-conc.qmd
          text: Integrated Abundancy by Morphogroup
        - href: supp_04_all-copepod-occurrence.qmd
          text: All Copepod Occupancy

    tools:
      - icon: github
        href: https://github.com/TheAlexBarth/DMV_BATS
      - icon: house-fill
        href: https://thealexbarth.github.io/#about

format:
  html:
    theme: journal
    css: styles.css
    code-fold: true
    code-tools: true
    
execute: 
  warning: false

editor: visual
