---
title: DVM and Daytime depth model
---

```{r}
rm(list = ls())
library(EcotaxaTools)
library(ggplot2)
library(ggpubr)
library(lubridate)
library(dplyr)
library(mgcv)
source('../R/tools.R')

# |- load in data ---------------------------------------------
wmd_data <- readRDS('../data/04_wmd-by-cruise.rds')
uvp_data_meta <- readRDS('../data/01_uvp-trim-final.rds')$meta
uvp_data_meta$cruise_id <- paste0(uvp_data_meta$stationid,
                                  uvp_data_meta$programid)

uvp_data_meta$dateabv <- paste(year(uvp_data_meta$sampledate),
                               month(uvp_data_meta$sampledate),
                               '01', sep = '-') |> 
  as.Date()


sat_data <- readRDS('../data/05_modis-month-sum.rds')
sat_data$Date <- paste(year(sat_data$Date),
                       month(sat_data$Date),
                       '01',sep ='-') |> 
  as.Date()


part_data <- readRDS('../data/05_cast-metrics.rds')
part_data$sampledate <- paste(year(part_data$sampledate),
                               month(part_data$sampledate),
                               '01', sep = '-') |> 
  as.Date()

part_data <- part_data[order(part_data$profileid, uvp_data_meta$profileid),]
part_data$cruise_id <- uvp_data_meta$cruise_id
part_data_cruise <- part_data |> 
  group_by(cruise_id) |> 
  summarise(dcm_d = mean(dcm_d,na.rm = T),
            intg_part = mean(intg_part, na.rm = T))

# |- format wmd CIs for each cruise --------------------------
wmd_df <- wmd_df_construct(wmd_data,'cruise')
wmd_df$date <- wmd_df$date |> as.Date(origin = '1970-01-01')

# |- pull all together ----------------------------
full_data <- wmd_df
full_data$par <- rep(NA,nrow(full_data))
full_data$dwi <- rep(NA, nrow(full_data))
full_data$dcm_d <- rep(NA,nrow(full_data))
full_data$part250 <- rep(NA,nrow(full_data))

for(i in 1:length(unique(full_data$cruise_id))) {
  cruise <-  unique(full_data$cruise_id)[i]
  full_idx <- which(full_data$cruise_id == cruise)
  part_idx <- which(part_data_cruise$cruise_id == cruise)
  date <- full_data$date[full_idx] |> unique()
  sat_idx <- which(sat_data$Date == date)
  
  full_data$par[full_idx] <- sat_data$par[sat_idx]
  full_data$dwi[full_idx] <- sat_data$dwi[sat_idx]
  full_data$dcm_d[full_idx] <- part_data_cruise$dcm_d[part_idx]
  full_data$part250[full_idx] <- part_data_cruise$intg_part[part_idx]
}

```


Now, models will be constructed to see if there is a clear relationship between environmental variables and DVM distance

```{r}
dvm <- full_data[full_data$metric == 'dn_diff',]

# mod_list <- vector('list',length(unique(dvm$cluster)))
# 
# for(i in 1:length(mod_list)) {
#   temp_df <- dvm[dvm$cluster == unique(dvm$cluster)[i],]
#   mod_list[[i]] <- lm(mid ~ (par) + (dwi) + (dcm_d) + (part250),
#                       data = temp_df)
# }

# plotting all the variables
par_plot <- ggplot(dvm) +
  geom_point(aes(x = par,
                 y = mid,
                 color = cluster,
                 shape = cluster),
             size = 2) +
  scale_color_manual(values = gg_cbb_col(4)) +
  labs(x = 'PAR', y = 'DVM Amplitude') +
  theme_pubr()


dwi_plot <- ggplot(dvm) +
  geom_point(aes(x = dwi,
                 y = mid,
                 color = cluster,
                 shape = cluster),
             size = 2) +
  scale_color_manual(values = gg_cbb_col(4)) +
  labs(x = '1/k490', y = 'DVM Amplitude') +
  theme_pubr()

dcm_d_plot <- ggplot(dvm) +
  geom_point(aes(x = dcm_d,
                 y = mid,
                 color = cluster,
                 shape = cluster),
             size = 2) +
  scale_color_manual(values = gg_cbb_col(4)) +
  labs(x = 'DCM Depth [m]', y = 'DVM Amplitude') +
  theme_pubr()

part_plot <- ggplot(dvm) +
  geom_point(aes(x = part250,
                 y = mid,
                 color = cluster,
                 shape = cluster),
             size = 2) +
  scale_color_manual(values = gg_cbb_col(4)) +
  labs(x = 'Integrated Euphotic Particle', y = 'DVM Amplitude') +
  theme_pubr()


ggarrange(par_plot, dwi_plot,
          dcm_d_plot, part_plot,
          common.legend = T,
          nrow = 2, ncol = 2)
```



```{r}
day_df <- full_data[full_data$metric == 'wmd_d',]

# mod_list <- vector('list',length(unique(day_df$cluster)))
# 
# for(i in 1:length(mod_list)) {
#   temp_df <- day_df[day_df$cluster == unique(day_df$cluster)[i],]
#   mod_list[[i]] <- lm(mid ~ s(par) + s(dwi) + s(dcm_d) + s(part250),
#                       data = temp_df)
# }

# plotting all the variables
par_plot <- ggplot(day_df) +
  geom_point(aes(x = par,
                 y = mid,
                 color = cluster,
                 shape = cluster),
             size = 2) +
  scale_color_manual(values = gg_cbb_col(4)) +
  labs(x = 'PAR', y = 'Daytime WMD') +
  theme_pubr()


dwi_plot <- ggplot(day_df) +
  geom_point(aes(x = dwi,
                 y = mid,
                 color = cluster,
                 shape = cluster),
             size = 2) +
  scale_color_manual(values = gg_cbb_col(4)) +
  labs(x = '1/k490', y = 'Daytime WMD') +
  theme_pubr()

dcm_d_plot <- ggplot(day_df) +
  geom_point(aes(x = dcm_d,
                 y = mid,
                 color = cluster,
                 shape = cluster),
             size = 2) +
  scale_color_manual(values = gg_cbb_col(4)) +
  labs(x = 'DCM Depth [m]', y = 'Daytime WMD') +
  theme_pubr()

part_plot <- ggplot(day_df) +
  geom_point(aes(x = part250,
                 y = mid,
                 color = cluster,
                 shape = cluster),
             size = 2) +
  scale_color_manual(values = gg_cbb_col(4)) +
  labs(x = 'Integrated Euphotic Particle', y = 'Daytime WMD') +
  theme_pubr()


ggarrange(par_plot, dwi_plot,
          dcm_d_plot, part_plot,
          common.legend = T,
          nrow = 2, ncol = 2)
```
